# SOCIALS REDIRECTS
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/dsc"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/dc"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/facebook"
  to = "https://facebook.com/groups/gractwo"

[[redirects]]
  from = "/fb"
  to = "https://facebook.com/groups/gractwo"

[[redirects]]
  from = "/github"
  to = "https://github.com/gractwo"

[[redirects]]
  from = "/gh"
  to = "https://github.com/gractwo"

# 'funny' REDIRECTS
[[redirects]]
  from = "/pgtf-theme"
  to = "https://www.youtube.com/watch?v=zjedLeVGcfE"