# SOCIALS REDIRECTS
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/dsc"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/dc"
  to = "https://discord.gg/NBXq95C"

[[redirects]]
  from = "/facebook"
  to = "https://facebook.com/groups/gractwo"

[[redirects]]
  from = "/fb"
  to = "https://facebook.com/groups/gractwo"

[[redirects]]
  from = "/github"
  to = "https://github.com/gractwo"

[[redirects]]
  from = "/gh"
  to = "https://github.com/gractwo"

# 'funny' REDIRECTS
[[redirects]]
  from = "/pgtf-theme"
  to = "https://www.youtube.com/watch?v=zjedLeVGcfE"

# PERSONAL REDIRECTS
[[redirects]]
  from = "/jamesen-external"
  to = "https://manczak.net"

[[redirects]]
  from = "/jamesen-steam"
  to = "https://steamcommunity.com/id/jakubmanczak/"

[[redirects]]
  from = "/jamesen-github"
  to = "https://github.com/jakubmanczak"

[[redirects]]
  from = "/jamesen-twitter"
  to = "https://twitter.com/j4kubmanczak"

[[redirects]]
  from = "/kuolek-steam"
  to = "https://steamcommunity.com/profiles/76561198381997060"

[[redirects]]
  from = "/kuolek-facebook"
  to = "https://www.facebook.com/olek.kulka.1"

[[redirects]]
  from = "/beelephant-steam"
  to = "https://steamcommunity.com/profiles/76561198309722571"

[[redirects]]
  from = "/mollin-anilist"
  to = "https://anilist.co/user/Mollin/"

[[redirects]]
  from = "/mollin-steam"
  to = "https://steamcommunity.com/profiles/76561198855251311"

[[redirects]]
  from = "/mollin-twitter"
  to = "https://twitter.com/mollin_j/"

[[redirects]]
  from = "/bavilgravlax-steam"
  to = "https://steamcommunity.com/profiles/76561198855251311"